// Lee Filters gel database.
// HEX values are visual approximations of the dyed filter color
// (i.e. what white light looks like after passing through the filter).
// Source: Lee Filters swatch book (numbers + names from leefilters.com).
//
// To extend: add new entries below. Future versions can add a `spectrum`
// field with sampled transmission per wavelength for true spectral math.

export type Gel = {
  number: string;
  name: string;
  hex: string;
};

export const GELS: Gel[] = [
  { number: "002", name: "Rose Pink", hex: "#f97dc8" },
  { number: "003", name: "Lavender Tint", hex: "#f1e4f5" },
  { number: "004", name: "Medium Bastard Amber", hex: "#fac8a8" },
  { number: "007", name: "Pale Yellow", hex: "#f6f4c2" },
  { number: "008", name: "Dark Salmon", hex: "#fbb59a" },
  { number: "009", name: "Pale Amber Gold", hex: "#fbd6a6" },
  { number: "010", name: "Medium Yellow", hex: "#fff200" },
  { number: "013", name: "Straw Tint", hex: "#ffe0a4" },
  { number: "015", name: "Deep Straw", hex: "#fbc02a" },
  { number: "017", name: "Surprise Peach", hex: "#e29274" },
  { number: "019", name: "Fire", hex: "#f1320c" },
  { number: "020", name: "Medium Amber", hex: "#fbb066" },
  { number: "021", name: "Gold Amber", hex: "#fa8b21" },
  { number: "022", name: "Dark Amber", hex: "#f06b18" },
  { number: "024", name: "Scarlet", hex: "#f15a4f" },
  { number: "025", name: "Sunset Red", hex: "#f38560" },
  { number: "026", name: "Bright Red", hex: "#dc1428" },
  { number: "027", name: "Medium Red", hex: "#c8102e" },
  { number: "029", name: "Plasa Red", hex: "#dc0a2d" },
  { number: "035", name: "Light Pink", hex: "#fbd0d6" },
  { number: "036", name: "Medium Pink", hex: "#f9b1c0" },
  { number: "046", name: "Dark Magenta", hex: "#d6296b" },
  { number: "048", name: "Rose Purple", hex: "#e988b8" },
  { number: "049", name: "Medium Purple", hex: "#a8268c" },
  { number: "052", name: "Light Lavender", hex: "#dcc5ec" },
  { number: "053", name: "Paler Lavender", hex: "#dde0ee" },
  { number: "058", name: "Lavender", hex: "#b48ee0" },
  { number: "061", name: "Mist Blue", hex: "#dceef2" },
  { number: "063", name: "Pale Blue", hex: "#cfe7f1" },
  { number: "068", name: "Sky Blue", hex: "#37a8e0" },
  { number: "071", name: "Tokyo Blue", hex: "#001ea0" },
  { number: "075", name: "Evening Blue", hex: "#7aa9e0" },
  { number: "079", name: "Just Blue", hex: "#3a8dd0" },
  { number: "085", name: "Deeper Blue", hex: "#0070ad" },
  { number: "088", name: "Lime Green", hex: "#d8f06a" },
  { number: "089", name: "Moss Green", hex: "#69c241" },
  { number: "090", name: "Dark Yellow Green", hex: "#1ea800" },
  { number: "100", name: "Spring Yellow", hex: "#fff300" },
  { number: "101", name: "Yellow", hex: "#fde400" },
  { number: "102", name: "Light Amber", hex: "#fbd96b" },
  { number: "103", name: "Straw", hex: "#fce6a8" },
  { number: "104", name: "Deep Amber", hex: "#fcc23e" },
  { number: "105", name: "Orange", hex: "#f59820" },
  { number: "106", name: "Primary Red", hex: "#e10a17" },
  { number: "107", name: "Light Rose", hex: "#f7adb4" },
  { number: "108", name: "English Rose", hex: "#fbc1b6" },
  { number: "109", name: "Light Salmon", hex: "#fdc1b3" },
  { number: "110", name: "Middle Rose", hex: "#f8b4c1" },
  { number: "111", name: "Dark Pink", hex: "#f497c0" },
  { number: "113", name: "Magenta", hex: "#ee1b6b" },
  { number: "115", name: "Peacock Blue", hex: "#1cd0b8" },
  { number: "116", name: "Medium Blue-Green", hex: "#16a4a0" },
  { number: "117", name: "Steel Blue", hex: "#bff0ee" },
  { number: "118", name: "Light Blue", hex: "#43d3f0" },
  { number: "119", name: "Dark Blue", hex: "#0f7ec0" },
  { number: "120", name: "Deep Blue", hex: "#0651a8" },
  { number: "121", name: "LEE Green", hex: "#bff070" },
  { number: "122", name: "Fern Green", hex: "#7be05a" },
  { number: "124", name: "Dark Green", hex: "#1aa869" },
  { number: "126", name: "Mauve", hex: "#a6238b" },
  { number: "127", name: "Smokey Pink", hex: "#c47080" },
  { number: "128", name: "Bright Pink", hex: "#f1308f" },
  { number: "130", name: "Clear", hex: "#ffffff" },
  { number: "131", name: "Marine Blue", hex: "#9aedd0" },
  { number: "132", name: "Medium Blue", hex: "#0096d6" },
  { number: "134", name: "Golden Amber", hex: "#f5a974" },
  { number: "135", name: "Deep Golden Amber", hex: "#f25c0a" },
  { number: "136", name: "Pale Lavender", hex: "#e6c7ee" },
  { number: "137", name: "Special Lavender", hex: "#c5b1e0" },
  { number: "138", name: "Pale Green", hex: "#b9eba0" },
  { number: "139", name: "Primary Green", hex: "#3fa835" },
  { number: "140", name: "Summer Blue", hex: "#9defe2" },
  { number: "141", name: "Bright Blue", hex: "#28cae6" },
  { number: "142", name: "Pale Violet", hex: "#a59ad8" },
  { number: "143", name: "Pale Navy Blue", hex: "#5fb6c0" },
  { number: "144", name: "No Color Blue", hex: "#9be0e2" },
  { number: "147", name: "Apricot", hex: "#f4a87b" },
  { number: "148", name: "Bright Rose", hex: "#ee3b6f" },
  { number: "151", name: "Gold Tint", hex: "#fbd6c5" },
  { number: "152", name: "Pale Gold", hex: "#facfbb" },
  { number: "153", name: "Pale Salmon", hex: "#fbd5cc" },
  { number: "154", name: "Pale Rose", hex: "#fbcdc4" },
  { number: "156", name: "Chocolate", hex: "#cda072" },
  { number: "157", name: "Pink", hex: "#f5868c" },
  { number: "158", name: "Deep Orange", hex: "#f48a23" },
  { number: "159", name: "No Colour Straw", hex: "#fbf6e0" },
  { number: "161", name: "Slate Blue", hex: "#9bd0f0" },
  { number: "162", name: "Bastard Amber", hex: "#fcd9c8" },
  { number: "164", name: "Flame Red", hex: "#f33d12" },
  { number: "165", name: "Daylight Blue", hex: "#62c8e8" },
  { number: "169", name: "Lilac Tint", hex: "#fbe2f0" },
  { number: "170", name: "Deep Lavender", hex: "#cba6df" },
  { number: "172", name: "Lagoon Blue", hex: "#2cd6c2" },
  { number: "174", name: "Dark Steel Blue", hex: "#bce0ee" },
  { number: "176", name: "Loving Amber", hex: "#fbb6a8" },
  { number: "179", name: "Chrome Orange", hex: "#fbb000" },
  { number: "180", name: "Dark Lavender", hex: "#b78fe0" },
  { number: "181", name: "Congo Blue", hex: "#5b1ea0" },
  { number: "182", name: "Light Red", hex: "#ed1c24" },
  { number: "183", name: "Moonlight Blue", hex: "#34d6ee" },
  { number: "192", name: "Flesh Pink", hex: "#f7a3b8" },
  { number: "194", name: "Surprise Pink", hex: "#bea1de" },
  { number: "195", name: "Zenith Blue", hex: "#0560c8" },
  { number: "196", name: "True Blue", hex: "#7ea7e0" },
  { number: "197", name: "Alice Blue", hex: "#90b4e2" },
  { number: "198", name: "Palace Blue", hex: "#7790d0" },
  { number: "199", name: "Regal Blue", hex: "#7e85cc" },
  { number: "200", name: "Double C.T. Blue", hex: "#90a8de" },
  { number: "201", name: "Full C.T. Blue", hex: "#a4bee8" },
  { number: "202", name: "Half C.T. Blue", hex: "#bcd0ec" },
  { number: "203", name: "Quarter C.T. Blue", hex: "#d6e4f1" },
  { number: "204", name: "Full C.T. Orange", hex: "#fcb872" },
  { number: "205", name: "Half C.T. Orange", hex: "#fbe0bb" },
  { number: "206", name: "Quarter C.T. Orange", hex: "#fce8c9" },
  { number: "207", name: "Full C.T.O. + .3 ND", hex: "#e2a374" },
  { number: "208", name: "Full C.T.O. + .6 ND", hex: "#c98c5e" },
  { number: "212", name: "L.C.T. Yellow", hex: "#fbf6c4" },
  { number: "213", name: "White Flame Green", hex: "#dff0c8" },
  { number: "218", name: "Eighth C.T. Blue", hex: "#e8f0f7" },
  { number: "219", name: "Fluorescent Green", hex: "#a8d098" },
  { number: "223", name: "Eighth C.T. Orange", hex: "#fbe9d3" },
  { number: "230", name: "Super Correction LCT-Y", hex: "#d4b685" },
  { number: "232", name: "Super White Flame Green", hex: "#fbcdb0" },
  { number: "236", name: "HMI to Tungsten", hex: "#fbc99c" },
  { number: "237", name: "C.I.D. to Tungsten", hex: "#fbb69a" },
  { number: "238", name: "C.S.I. to Tungsten", hex: "#fbb6a3" },
  { number: "241", name: "LEE Fluorescent 5700K", hex: "#a8d6c3" },
  { number: "242", name: "LEE Fluorescent 4300K", hex: "#c0e6cc" },
  { number: "243", name: "LEE Fluorescent 3600K", hex: "#bce8a8" },
  { number: "244", name: "LEE Plus Green", hex: "#cce8a8" },
  { number: "245", name: "LEE Half Plus Green", hex: "#dce8b8" },
  { number: "246", name: "LEE Quarter Plus Green", hex: "#e6f0d4" },
  { number: "247", name: "LEE Minus Green", hex: "#fad6e2" },
  { number: "248", name: "LEE Half Minus Green", hex: "#fbe4ee" },
  { number: "249", name: "LEE Quarter Minus Green", hex: "#fceaf2" },
  { number: "278", name: "Eighth Plus Green", hex: "#f0f6e6" },
  { number: "279", name: "Eighth Minus Green", hex: "#fceff5" },
  { number: "281", name: "3/4 C.T.B.", hex: "#cce0f1" },
  { number: "283", name: "1.5 C.T. Blue", hex: "#bedaee" },
  { number: "285", name: "3/4 C.T. Orange", hex: "#fbcb95" },
  { number: "286", name: "1.5 C.T. Orange", hex: "#fbb672" },
  { number: "287", name: "Double C.T. Orange", hex: "#f7a85a" },
  { number: "322", name: "Soft Green", hex: "#3eddae" },
  { number: "323", name: "Jade", hex: "#1ec98a" },
  { number: "327", name: "Forest Green", hex: "#1b8a4c" },
  { number: "328", name: "Follies Pink", hex: "#f078b6" },
  { number: "332", name: "Special Rose Pink", hex: "#ee2a78" },
  { number: "343", name: "Special Medium Lavender", hex: "#7a18b8" },
  { number: "345", name: "Fuchsia Pink", hex: "#c34dc8" },
  { number: "352", name: "Glacier Blue", hex: "#26c8e6" },
  { number: "353", name: "Lighter Blue", hex: "#27dec4" },
  { number: "354", name: "Special Steel Blue", hex: "#1cd6b6" },
  { number: "363", name: "Special Medium Blue", hex: "#0773c0" },
  { number: "366", name: "Cornflower", hex: "#a3d4ee" },
  { number: "441", name: "Full C.T. Straw", hex: "#fbb56a" },
  { number: "442", name: "Half C.T. Straw", hex: "#fbd5a6" },
  { number: "443", name: "Quarter C.T. Straw", hex: "#fbe2c0" },
  { number: "444", name: "Eighth C.T. Straw", hex: "#fbecd2" },
  { number: "500", name: "Double New Color Blue", hex: "#a6c1e6" },
  { number: "501", name: "New Color Blue", hex: "#bcd0ee" },
  { number: "502", name: "Lavender Blue", hex: "#d4e4f1" },
  { number: "503", name: "Cool Lavender", hex: "#e2eaf2" },
  { number: "504", name: "Cool Lavender 2", hex: "#cae6cd" },
  { number: "505", name: "Sally Green", hex: "#dff05a" },
  { number: "506", name: "Marlene", hex: "#fbd6c2" },
  { number: "507", name: "Madge", hex: "#f43c0c" },
  { number: "508", name: "Midnight Blue", hex: "#5e6ac8" },
  { number: "525", name: "Daylight Blue Frost", hex: "#7aa1e0" },
  { number: "550", name: "Eighth C.T.S.", hex: "#cdb852" },
  { number: "600", name: "0.15 ND", hex: "#a6a6a6" },
  { number: "601", name: "0.3 ND", hex: "#9ea3a3" },
  { number: "602", name: "0.6 ND", hex: "#909494" },
  { number: "603", name: "0.9 ND", hex: "#bcbcbc" },
  { number: "642", name: "Half Mustard Yellow", hex: "#a89318" },
  { number: "650", name: "Industry Sodium", hex: "#b39865" },
  { number: "651", name: "Hi-Sodium", hex: "#f5a468" },
  { number: "652", name: "Urban Sodium", hex: "#f78b3d" },
  { number: "653", name: "Deep Sodium", hex: "#7a4818" },
  { number: "700", name: "Perfect Lavender", hex: "#9908d6" },
  { number: "702", name: "Special Pale Lavender", hex: "#dcb6ee" },
  { number: "703", name: "Cold Lavender", hex: "#bf6ad6" },
  { number: "704", name: "Lily", hex: "#e69cee" },
  { number: "706", name: "King Fals Lavender", hex: "#876ec8" },
  { number: "707", name: "Ultimate Violet", hex: "#5e1ea0" },
  { number: "708", name: "Cool Lavender Tint", hex: "#dce6ee" },
  { number: "709", name: "Electric Lilac", hex: "#dce0ee" },
  { number: "710", name: "Spir Special Blue", hex: "#0010a0" },
  { number: "711", name: "Cold Blue", hex: "#a4b6d6" },
  { number: "712", name: "Bedford Blue", hex: "#7e90c8" },
  { number: "713", name: "J. Winter Blue", hex: "#000a90" },
  { number: "714", name: "Soft Blue", hex: "#3878c8" },
  { number: "715", name: "Cabana Blue", hex: "#2e80c8" },
  { number: "716", name: "Mikkel Blue", hex: "#0078d6" },
  { number: "719", name: "Colour Wash Blue", hex: "#a4c0e0" },
  { number: "721", name: "Berry Blue", hex: "#0078e0" },
  { number: "722", name: "Bray Blue", hex: "#0086d6" },
  { number: "723", name: "Virgin Blue", hex: "#3878c8" },
  { number: "724", name: "Ocean Blue", hex: "#7ee6f0" },
  { number: "725", name: "Old Steel Blue", hex: "#bef0f0" },
  { number: "727", name: "Aquamarine", hex: "#3ac8c8" },
  { number: "728", name: "Steel Green", hex: "#cde6dc" },
  { number: "729", name: "Scuba Blue", hex: "#1ca890" },
  { number: "730", name: "Liberty Green", hex: "#cce8d4" },
  { number: "731", name: "Dirty Ice", hex: "#e2eee0" },
  { number: "733", name: "Damp Squib", hex: "#dee6c8" },
  { number: "735", name: "Velvet Green", hex: "#3ac888" },
  { number: "736", name: "Twickenham Green", hex: "#22a02b" },
  { number: "738", name: "JAS Green", hex: "#a6f015" },
  { number: "740", name: "Aurora Borealis Green", hex: "#566d18" },
  { number: "741", name: "Mustard Yellow", hex: "#7d6818" },
  { number: "742", name: "Bram Brown", hex: "#cd9856" },
  { number: "744", name: "True Brown", hex: "#f3c688" },
  { number: "746", name: "Brown", hex: "#5a2e10" },
  { number: "747", name: "Easy White", hex: "#f9b8a0" },
  { number: "748", name: "Seedy Pink", hex: "#e6727e" },
  { number: "763", name: "Wheat", hex: "#fbeacc" },
  { number: "764", name: "Sun Colour Straw", hex: "#fbe6c2" },
  { number: "765", name: "Lee Sun Yellow", hex: "#fbe0a8" },
  { number: "767", name: "Oklahoma Yellow", hex: "#fbcc1a" },
  { number: "768", name: "Egg Yolk Yellow", hex: "#fab800" },
  { number: "770", name: "Burnt Yellow", hex: "#fb9a18" },
  { number: "773", name: "Cardbox Amber", hex: "#fbb89a" },
  { number: "776", name: "Wheatgerm", hex: "#fbc7a8" },
  { number: "777", name: "Rust", hex: "#e69020" },
  { number: "778", name: "Millennium Gold", hex: "#fb8c0c" },
  { number: "779", name: "Bastard Pink", hex: "#fba893" },
  { number: "780", name: "Astral Blue", hex: "#fb8a18" },
  { number: "787", name: "Marius Red", hex: "#a60a2c" },
  { number: "789", name: "Blood Red", hex: "#a4382c" },
  { number: "790", name: "Moroccan Pink", hex: "#fbb1a3" },
  { number: "793", name: "Vanity Fair", hex: "#f1297a" },
  { number: "794", name: "Pretty 'N Pink", hex: "#fbacc8" },
  { number: "795", name: "Magical Magenta", hex: "#ee52b8" },
  { number: "797", name: "Deep Purple", hex: "#a8108c" },
  { number: "798", name: "Chrysalis Pink", hex: "#9d28b8" },
  { number: "799", name: "Special KH Lavender", hex: "#3a18a0" },
];

export const GEL_MAP: Record<string, Gel> = Object.fromEntries(
  GELS.map((g) => [g.number, g]),
);
